### ISSUE TITLE
serverless version (wasm)

### ISSUE THREAD

**Issue by paulvollmer** [yuroyoro/goast-viewer#10]
hi,

at first 👍 for this great tool.

i refactored the code a bit and now the ast parser run at the browser. the go code is compiled to wasm and some small changes at the angular conde need to be done to make the serverless version.

if you like the idea, let me know and i prepare a PR.

**Comment by yuroyoro** [comment]
@paulvollmer That's great! Cloud you send a PR?

**Comment by paulvollmer** [comment]
@yuroyoro i'll send the PR, but i think you need to check and cleanup a bit more the angular app.
